[package]
name = "chip8-native"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"

[dependencies]
chip8 = { path = "../" }
sdl2 = { version = "0.34.2", features = [ "bundled" ] }
